[[pages]]
name = "Navigation"
icon = ":material/home:"
is_section = true

[[pages]]
name = "Home"
path = "streamlit_app.py"
icon = ":material/home:"

[[pages]]
name = "About Us"
path = "pages/about.py"
icon = ":material/person:"

[[pages]]
name = "Calculate"
path = "pages/app2.py"
icon = ":material/thumb_up:"

[[pages]]
name = "Dashboard"
path = "pages/dashboard.py"
icon = ":material/dashboard:"

[[pages]]
name = "Predictions"
path = "pages/success.py"
icon = ":material/check:"

[[pages]]
name = "Login"
path = "pages/login.py"
icon = ":material/login:"